pub mod apple;
pub mod browser;
pub mod cart;
pub mod comics;
pub mod computer;
pub mod desktop;
pub mod export;
pub mod google;
pub mod home;
pub mod news;
pub mod notion;
pub mod ollama;
pub mod reminders;
pub mod system;
pub mod vision;
#[cfg(feature = "desktop")]
pub mod voice;
pub mod weather;
